disabled_rules:
  - line_length
  - function_body_length
  - variable_name_max_length
  - variable_name_min_length
  - type_body_length
  - force_cast # Not sure I want this disabled... (GameCenter issues)